//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumCarsData
    {
        public int CarOwnerID { get; set; }
        public string CarOwnerName { get; set; }
        public string CarOwnerEmail { get; set; }
        public string SelectedCar { get; set; }
    }
}
